# 延迟检测 URL
p: &p
  {type: http, interval: 3600, header: {User-Agent: ["meta", "clash"]}, health-check: {enable: true, url: https://www.gstatic.com/generate_204, interval: 300, timeout: 5000, lazy: true}}

# 配置代理提供者
proxy-providers:
  # 第一个代理提供者
  provider1:
    <<: *p  # 继承通用配置
    url: "https://ghp.ci/https://raw.githubusercontent.com/mfbpn/tg_mfbpn_sub/main/trial.yaml"

  # 第二个代理提供者
  provider2:
    <<: *p  # 继承通用配置
    url: "https://ghp.ci/https://raw.githubusercontent.com/snakem982/proxypool/main/source/clash-meta.yaml"

# URL 测试配置
u:: &u
  type: url-test  # 测试类型
  use:
    - provider1   # 使用第一个代理提供者
    - provider2   # 使用第二个代理提供者

port: 7890  # HTTP 代理端口
socks-port: 7891  # SOCKS5 代理端口
mixed-port: 10801  # HTTP/SOCKS 混合代理端口
redir-port: 9797  # 重定向端口，用于透明代理
tproxy-port: 9898  # TProxy 端口，支持 TUN 模式
allow-lan: true  # 允许局域网设备连接代理
bind-address: "*"  # 绑定地址，默认为所有 IP 地址
authentication:
  - "username:password"  # HTTP/SOCKS 代理认证，格式为 用户名:密码
skip-auth-prefixes:
  - 127.0.0.1/8  # 跳过本地地址的认证
  - ::1/128  # 跳过 IPv6 本地地址的认证
lan-allowed-ips:
  - 0.0.0.0/0  # 允许局域网访问的 IP 地址范围 (IPv4)
  - ::/0  # 允许局域网访问的 IP 地址范围 (IPv6)
lan-disallowed-ips:
  - 192.168.0.3/32  # 局域网禁止访问的特定 IP 地址
find-process-mode: strict  # 查找进程模式，严格模式
mode: rule  # 工作模式为规则模式
geodata-mode: true  # GEOIP 数据模式，mmdb 或者 dat
geodata-loader: memconservative  # GEO 文件加载模式
geox-url:  # Geo 数据库配置，用于地理位置和 ASN 匹配
  geoip: "https://ghp.ci/https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geoip.dat"  # GeoIP 数据库
  geosite: "https://ghp.ci/https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat"  # GeoSite 数据库
  mmdb: "https://ghp.ci/https://github.com/Loyalsoldier/geoip/releases/latest/download/Country.mmdb"  # MaxMind GeoLite2 数据库
  asn: "https://ghp.ci/https://github.com/Loyalsoldier/geoip/blob/release/GeoLite2-ASN.mmdb"  # ASN 数据库
geo-auto-update: true  # 开启自动更新 Geo 数据库
geo-update-interval: 24  # Geo 数据库更新间隔 (单位: 小时)
geosite-matcher: succinct  # Geosite 匹配模式
global-ua: clash.meta  # 自定全局 UA
etag-support: true  # 外部资源下载的 ETag 支持
log-level: info  # 日志等级
ipv6: true  # 启用 IPv6
tls:  # TLS 相关配置
  certificate: string  # TLS 证书
  private-key: string  # TLS 私钥
  custom-certifactes:  # 自定义证书
    - |
      -----BEGIN CERTIFICATE-----
      format/pem...
      -----END CERTIFICATE-----
external-controller: 0.0.0.0:9093  # 外部控制端口
external-controller-tls: 0.0.0.0:9443  # TLS 外部控制端口
secret: ""  # 控制接口密钥
external-controller-cors:  # CORS 配置
  allow-origins:
    - "*"  # 允许所有来源
  allow-private-network: true  # 允许私有网络访问
external-controller-unix: mihomo.sock  # Unix Socket 控制接口
external-controller-pipe: \\.\pipe\mihomo  # Windows 管道接口
unified-delay: true  # 开启统一延迟时
tcp-concurrent: true  # 启用 TCP 并发连接
external-ui: ui  # 外部 UI 目录
external-ui-name: xd  # 外部 UI 名称
external-ui-url: "https://ghp.ci/https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip"  # 外部 UI 下载链接
external-doh-server: /dns-query  # 外部 DoH 服务器
interface-name: en0  # 使用的网络接口名称
routing-mark: 6666  # 路由标记
global-client-fingerprint: chrome  # 全局客户端指纹为 Chrome
disable-keep-alive: true  # 启用 Keep-Alive
keep-alive-idle: 15  # Keep-Alive 空闲时间 (单位: 秒)
keep-alive-interval: 15  # Keep-Alive 间隔时间 (单位: 秒)
experimental:  # 实验性功能配置
  quic-go-disable-gso: true  # 禁用 QUIC 协议中的 GSO (Generic Segmentation Offload) 功能
hosts:  # 本地 DNS 解析配置

profile:
  store-selected: true  # 存储已选择的代理组
  store-fake-ip: true  # 存储 Fake IP 地址

# 网络时间协议 (NTP) 设置
ntp:
  enable: true  # 启用 NTP 功能
  write-to-system: true  # 将同步的时间写入系统时钟
  server: ntp.ntsc.ac.cn  # NTP 服务器地址
  port: 123  # NTP 服务器端口，默认使用 123 端口
  interval: 30  # 同步时间的间隔 (单位: 分钟)

# sniffer 配置：用于检测和处理不同协议的流量
sniffer:
  enable: false  # 是否启用 sniffer 侦测功能，默认关闭
  force-dns-mapping: true  # 强制映射 DNS 解析，即使有 IP 地址，仍将尝试解析域名
  parse-pure-ip: true  # 尝试将纯 IP 流量解析为域名，便于流量规则的匹配
  override-destination: false  # 是否覆盖目标地址（在某些情况下可能会破坏流量）

  sniff:
    HTTP:
      ports: [80, 8080-8880]  # 对 HTTP 流量进行嗅探的端口范围，常用于网站和应用
      override-destination: true  # 覆盖目标地址以强制流量走代理或规则匹配
    TLS:
      ports: [443, 8443]  # 对 HTTPS 流量的端口进行嗅探，通常用于加密连接
    QUIC:
      ports: [443, 8443]  # 对 QUIC 协议的流量进行嗅探，QUIC 常用于改进 HTTPS 连接的速度

  force-domain:
    - +.v2ex.com  # 对指定域名强制解析，即使 IP 地址已缓存或已知

  skip-domain:
    - Mijia Cloud  # 跳过指定域名，不对其进行嗅探处理（如智能家居流量）

  skip-src-address:
    - 192.168.0.3/32  # 跳过来源 IP 地址，不对其进行嗅探

  skip-dst-address:
    - 192.168.0.3/32  # 跳过目标 IP 地址，不对其进行嗅探

# tun 配置：用于启用 TUN 模式，优化流量路由和 IP 设置
tun:
  enable: true  # 启用 TUN 模式，用于透明代理
  stack: gvisor  # 使用空间网络栈处理流量，可用值： system/gvisor/mixed
  auto-route: true  # 自动根据流量选择最佳路由
  auto-redirect: true  # 自动重定向不匹配规则的流量
  auto-detect-interface: true  # 自动检测并使用适当的网络接口
  dns-hijack:
    - any:53  # 劫持所有 53 端口的 DNS 请求
    - tcp://any:53  # 劫持所有 TCP 53 端口的 DNS 请求
  device: utun0  # 指定 TUN 设备名称，默认为 utun0
  mtu: 9000  # 设置最大传输单元 (MTU)，提高网络吞吐量
  strict-route: true  # 强制使用严格路由，避免流量被错误路由
  gso: true  # 启用通用分段卸载 (GSO)，提高网络性能
  gso-max-size: 65536  # 设置 GSO 最大分段大小为 65536 字节
  udp-timeout: 300  # 设置 UDP 超时时间为 300 秒，优化 NAT 映射
  iproute2-table-index: 2022  # 使用指定的路由表索引 (iproute2)
  iproute2-rule-index: 9000  # 设置路由规则的索引 (iproute2)
  endpoint-independent-nat: false  # 禁用基于端点的 NAT 独立性
  route-address-set: []
  #  - ruleset-1 # 使用指定规则集管理路由
  route-exclude-address-set: []
  #  - ruleset-2  # 排除指定规则集中的地址
  route-address:
    - 0.0.0.0/1  # 路由 IPv4 流量，覆盖第一半部分地址
    - 128.0.0.0/1  # 路由 IPv4 流量，覆盖第二半部分地址
    - "::/1"  # 路由 IPv6 流量，覆盖第一半部分地址
    - "8000::/1"  # 路由 IPv6 流量，覆盖第二半部分地址
  route-exclude-address:
    - 192.168.0.0/16  # 排除私有 IPv4 地址范围
    - fc00::/7  # 排除私有 IPv6 地址范围
  include-interface: []
  #  - eth0  # 仅包含 eth0 接口的流量
  exclude-interface: []
  #  - eth1  # 排除 eth1 接口的流量
  include-uid: []
  #  - 0  # 包含 UID 为 0（通常是 root 用户）的流量
  include-uid-range: []
  #  - 1000:9999  # 包含 UID 范围为 1000:9999 的流量
  exclude-uid: []
  #  - 1000  # 排除 UID 为 1000 的流量
  exclude-uid-range: []
  #  - 1000:9999  # 排除 UID 范围为 1000:9999 的流量
  include-android-user: []
  #  - 0  # 包含 Android 用户 ID 为 0 的流量
  #  - 10  # 包含 Android 用户 ID 为 10 的流量
  include-package: []
  #  - com.android.chrome  # 仅包含指定 Android 应用 (Chrome) 的流量
  exclude-package: []
  #  - com.android.captiveportallogin  # 排除指定 Android 应用 (Captive Portal) 的流量

# DNS 配置：控制 DNS 查询行为，支持增强模式和假 IP 功能
dns:
  enable: true  # 启用 DNS 模块
  prefer-h3: true  # 是否优先使用 HTTP/3 进行 DNS 查询
  use-hosts: true  # 使用配置中的 hosts 文件条目
  use-system-hosts: true  # 使用系统的 hosts 文件条目
  respect-rules: true  # dns 连接遵守路由规则，需配置 proxy-server-nameserver
  listen: 0.0.0.0:1053  # 本地 DNS 监听端口，默认是 1053 端口
  ipv6: true  # 启用 IPv6 DNS 解析，避免 IPv6 地址的解析请求
  default-nameserver:
    - 223.5.5.5  # 默认使用阿里 DNS 服务器（中国）
    - "[2400:3200::1]"  # 默认 IPv6 DNS 服务器，使用阿里云的公共 DNS
  enhanced-mode: redir-host  # 启用增强模式，使用假 IP 技术
  fake-ip-range: 198.18.0.1/16  # 假 IP 的地址范围，用于伪装未匹配域名的 IP
  fake-ip-filter-mode: blacklist  # 假 IP 过滤模式：使用黑名单模式
  fake-ip-filter:
    - "*.lan"  # 局域网域名不使用假 IP，确保本地网络正常解析
  nameserver-policy:
    "geosite:cn,private":  # 针对中国和私有域名使用特定 DNS 策略
      - "tls://dns.alidns.com"  # 使用阿里 DNS 的加密传输协议
    "geosite:!cn,!private":  # 非中国和非私有域名使用不同的 DNS 服务器
      - "tls://dns.google"  # Google DNS over TLS
      - "tls://cloudflare-dns.com"  # Cloudflare DNS over TLS
  nameserver:
    - "tls://dns.alidns.com"  # 默认的 DNS over TLS 服务器，使用阿里 DNS
  fallback:
    - "tls://dns.google"  # 回退 DNS 服务器，使用 Google DNS
    - "tls://cloudflare-dns.com"  # Cloudflare DNS 作为回退
  proxy-server-nameserver:
    - "tls://dns.alidns.com"  # 直连使用阿里 DNS over TLS 服务器
  direct-nameserver:
    - dhcp://en0
    - system
  direct-nameserver-follow-policy: true  # 直连遵循 nameserver-policy 策略
  fallback-filter:
    geoip: true  # 启用基于地理位置的 IP 过滤
    geoip-code: CN  # 使用中国作为地理位置过滤的国家代码
    geosite:
      - gfw  # 使用防火长城 (GFW) 规则进行域名过滤
    ipcidr:
      - 240.0.0.0/4  # 排除某些保留的 IP 范围
    domain:
      - "+.google.com"  # 将 Google 域名添加到回退 DNS 过滤
      - "+.facebook.com"  # 将 Facebook 域名添加到回退 DNS 过滤
      - "+.youtube.com"  # 将 YouTube 域名添加到回退 DNS 过滤
    rule-set:
      - ProxyGFWlist
      - ProxyLite
      - ProxyMedia
      

proxies:
  - {name: "🎯全球直连", type: direct, udp: true}
  - {name: "⛔️广告拦截", type: reject, udp: true}

proxy-groups:
  - {name: 🚀节点选择, type: select, proxies: [🎯全球直连, ♻️自动选择, ⚡️均衡负载, 🔯故障转移, 📦全部节点, 🇭🇰香港, 🇹🇼台湾, 🇯🇵日本, 🇺🇸美国, 🇸🇬新加坡, 🇺🇸洛杉矶, 🇬🇧英国, 🇩🇪德国, 🇫🇷法国, 🇨🇦加拿大, 🇦🇺澳大利亚, 🇰🇷韩国, 🇷🇺俄罗斯, 🇳🇱荷兰, 🇮🇳印度, 🇲🇾马来西亚, 🇵🇱波兰, 🇪🇪爱沙尼亚, 🇦🇪阿联酋, 🇳🇬尼日利亚, 🇧🇬保加利亚, 🇸🇨塞舌尔, 🇪🇸西班牙, 🇻🇳越南, 🇸🇽荷属圣马丁, 🇲🇴澳门, 🇵🇭菲律宾, 🇹🇭泰国, 🇲🇳蒙古, 🌐其它地区]}

  - {name: 🚫广告拦截, type: select, proxies: [⛔️广告拦截, 🎯全球直连, 🚀节点选择]}

  - {name: ♻️自动选择, <<: *u, interval: 2, type: url-test}

  - {name: ⚡️均衡负载, <<: *u, strategy: round-robin, type: load-balance}

  - {name: 🔯故障转移, <<: *u, type: fallback}

  - {name: 📦全部节点, <<: *u, type: select}

  - {name: 🇭🇰香港, <<: *u, filter: "(?i)🇭🇰|香港|hk_|hongkong|hong kong"}
  
  - {name: 🇹🇼台湾, <<: *u, filter: "(?i)🇹🇼|台湾|tw_|taiwan|tai wan"}
  
  - {name: 🇯🇵日本, <<: *u, filter: "(?i)🇯🇵|日本|jp_|japan"}
  
  - {name: 🇺🇸美国, <<: *u, filter: "(?i)🇺🇸|美国|us_|unitedstates|united states"}
  
  - {name: 🇸🇬新加坡, <<: *u, filter: "(?i)🇸🇬|新加坡|sg_|singapore"}
  
  - {name: 🇺🇸洛杉矶, <<: *u, filter: "(?i)洛杉矶|l.a._|losangeles|la sangeles"}
  
  - {name: 🇩🇪德国, <<: *u, filter: "(?i)🇩🇪|德国|de_|germany"}
  
  - {name: 🇫🇷法国, <<: *u, filter: "(?i)🇫🇷|法国|fr_|france"}
  
  - {name: 🇨🇦加拿大, <<: *u, filter: "(?i)🇨🇦|加拿大|ca_|canada"}
  
  - {name: 🇦🇺澳大利亚, <<: *u, filter: "(?i)🇦🇺|澳大利亚|au_|australia"}
  
  - {name: 🇰🇷韩国, <<: *u, filter: "(?i)🇰🇷|韩国|kr_|korea|southkorea|south korea"}
  
  - {name: 🇷🇺俄罗斯, <<: *u, filter: "(?i)🇷🇺|俄罗斯|ru_|russia"}
  
  - {name: 🇳🇱荷兰, <<: *u, filter: "(?i)🇳🇱|荷兰|nl_|netherlands|holland"}
  
  - {name: 🇮🇳印度, <<: *u, filter: "(?i)🇮🇳|印度|in_|india"}
  
  - {name: 🇲🇾马来西亚, <<: *u, filter: "(?i)🇲🇾|马来西亚|my_|malaysia"}

  - {name: 🇵🇱波兰, <<: *u, filter: "(?i)🇵🇱|波兰|pl_|poland"}

  - {name: 🇪🇪爱沙尼亚, <<: *u, filter: "(?i)🇪🇪|爱沙尼亚|ee_|estonia"}

  - {name: 🇦🇪阿联酋, <<: *u, filter: "(?i)🇦🇪|阿联酋|ae_|uae|unitedarabemirates|united arab emirates"}

  - {name: 🇳🇬尼日利亚, <<: *u, filter: "(?i)🇳🇬|尼日利亚|ng_|nigeria"}

  - {name: 🇧🇬保加利亚, <<: *u, filter: "(?i)🇧🇬|保加利亚|bg_|bulgaria"}

  - {name: 🇸🇨塞舌尔, <<: *u, filter: "(?i)🇸🇨|塞舌尔|sc_|seychelles"}

  - {name: 🇬🇧英国, <<: *u, filter: "(?i)🇬🇧|英国|gb_|greatbritain|great britain"}

  - {name: 🇪🇸西班牙, <<: *u, filter: "(?i)🇪🇸|西班牙|es_|spain"}
  
  - {name: 🇻🇳越南, <<: *u, filter: "(?i)🇻🇳|越南|vn_|vietnam"}

  - {name: 🇸🇽荷属圣马丁, <<: *u, filter: "(?i)🇸🇽|荷属圣马丁|nn_|sintmaarten|sint maarten|stmaarten|st maarten"}
  
  - {name: 🇲🇴澳门, <<: *u, filter: "(?i)🇲🇴|澳门|macao|mo_"}
  
  - {name: 🇵🇭菲律宾, <<: *u, filter: "(?i)🇵🇭|菲律宾|pilipinas|ph_"}
  
  - {name: 🇹🇭泰国, <<: *u, filter: "(?i)🇹🇭|泰国|thailand|th_"}
  
  - {name: 🇲🇳蒙古, <<: *u, filter: "(?i)🇲🇳|蒙古|mongolia|mn_"}

  - {name: 🌐其它地区, <<: *u, type: select, filter: "(?i)^(?!.*(?:🇭🇰|香港|hk_|hongkong|hong kong|🇹🇼|台湾|tw_|taiwan|tai wan|🇯🇵|日本|jp_|japan|🇺🇸|美国|us_|unitedstates|united states|🇸🇬|新加坡|sg_|singapore|🇺🇸洛杉矶|洛杉矶|l.a._|losangeles|la sangeles|🇩🇪|德国|de_|germany|🇫🇷|法国|fr_|france|🇨🇦|加拿大|ca_|canada|🇦🇺|澳大利亚|au_|australia|🇰🇷|韩国|kr_|korea|southkorea|south korea|🇷🇺|俄罗斯|ru_|russia|🇳🇱|荷兰|nl_|netherlands|holland|🇮🇳|印度|in_|india|🇲🇾|马来西亚|my_|malaysia|🇵🇱|波兰|pl_|poland|🇪🇪|爱沙尼亚|ee_|estonia|🇦🇪|阿联酋|ae_|uae|unitedarabemirates|united arab emirates|🇳🇬|尼日利亚|ng_|nigeria|🇧🇬|保加利亚|bg_|bulgaria|🇸🇨|塞舌尔|sc_|seychelles|🇬🇧|英国|gb_|greatbritain|great britain|🇪🇸|西班牙|es_|spain|🇻🇳|越南|vn_|vietnam|🇸🇽|荷属圣马丁|nn_|sintmaarten|sint maarten|stmaarten|st maarten|🇲🇴|澳门|macao|mo_|🇵🇭|菲律宾|pilipinas|ph_|🇹🇭|泰国|thailand|th_|🇲🇳|蒙古|mongolia|mn_)).*$"}

rules:
  # 广告拦截
  - RULE-SET,anti-AD-white,🎯全球直连 #白名单
  - RULE-SET,UnBan,🎯全球直连 #白名单
  - RULE-SET,anti-AD,🚫广告拦截
  - GEOSITE,category-ads-all,🚫广告拦截
  - RULE-SET,AD,🚫广告拦截
  - RULE-SET,Advertising,🚫广告拦截
  - RULE-SET,AdvertisingMiTV,🚫广告拦截
  - RULE-SET,BanAD,🚫广告拦截
  - RULE-SET,BanEasyList,🚫广告拦截
  - RULE-SET,BanEasyListChina,🚫广告拦截
  - RULE-SET,BanEasyPrivacy,🚫广告拦截
  - RULE-SET,BanProgramAD,🚫广告拦截
  - RULE-SET,EasyList,🚫广告拦截
  - RULE-SET,EasyListChina,🚫广告拦截
  - RULE-SET,EasyPrivacy,🚫广告拦截
  - RULE-SET,ProgramAD,🚫广告拦截
  - RULE-SET,reject,🚫广告拦截

  # 全球直连
  - RULE-SET,Apple,🎯全球直连
  - RULE-SET,ChinaDomain,🎯全球直连
  - RULE-SET,ChinaIpV6,🎯全球直连
  - RULE-SET,ChinaMedia,🎯全球直连
  - RULE-SET,Download,🎯全球直连
  - RULE-SET,LocalAreaNetwork,🎯全球直连
  - RULE-SET,MJJ,🎯全球直连
  - RULE-SET,ASNChina,🎯全球直连
  - GEOSITE,CN,🎯全球直连
  - GEOSITE,PRIVATE,🎯全球直连
  - RULE-SET,ChinaIp,🎯全球直连,no-resolve
  - RULE-SET,ChinaCompanyIp,🎯全球直连,no-resolve
  - GEOIP,CN,🎯全球直连,no-resolve
  - GEOIP,PRIVATE,🎯全球直连,no-resolve

  # 节点代理
  - MATCH,🚀节点选择

rule-anchor:
  ipcidr: &ipcidr {type: http, interval: 600, behavior: ipcidr, format: yaml}
  domain: &domain {type: http, interval: 600, behavior: domain, format: yaml}
  classical: &classical {type: http, interval: 600, behavior: classical, format: yaml}

rule-providers:
  # 域名规则
  AD:
    <<: *domain
    url: "https://ghp.ci/https://raw.githubusercontent.com/earoftoast/clash-rules/main/AD.yaml"
    path: ./ruleset/AD.yaml

  EasyList:
    <<: *domain
    url: "https://ghp.ci/https://raw.githubusercontent.com/earoftoast/clash-rules/main/EasyList.yaml"
    path: ./ruleset/EasyList.yaml

  EasyListChina:
    <<: *domain
    url: "https://ghp.ci/https://raw.githubusercontent.com/earoftoast/clash-rules/main/EasyListChina.yaml"
    path: ./ruleset/EasyListChina.yaml

  EasyPrivacy:
    <<: *domain
    url: "https://ghp.ci/https://raw.githubusercontent.com/earoftoast/clash-rules/main/EasyPrivacy.yaml"
    path: ./ruleset/EasyPrivacy.yaml

  ProgramAD:
    <<: *domain
    url: "https://ghp.ci/https://raw.githubusercontent.com/earoftoast/clash-rules/main/ProgramAD.yaml"
    path: ./ruleset/ProgramAD.yaml

  anti-AD:
    <<: *domain
    url: "https://ghp.ci/https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-clash.yaml"
    path: ./ruleset/anti-AD.yaml

  anti-AD-white:
    <<: *domain
    url: "https://ghp.ci/https://raw.githubusercontent.com/privacy-protection-tools/dead-horse/master/anti-ad-white-for-clash.yaml"
    path: ./ruleset/anti-AD-white.yaml

  reject:
    <<: *domain
    url: "https://ghp.ci/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/reject.txt"
    path: ./ruleset/reject.yaml

  # IP规则
  ChinaIp:
    <<: *ipcidr
    url: "https://ghp.ci/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/ChinaIp.yaml"
    path: ./ruleset/ChinaIp.yaml

  ChinaCompanyIp:
    <<: *ipcidr
    url: "https://ghp.ci/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/ChinaCompanyIp.yaml"
    path: ./ruleset/ChinaCompanyIp.yaml

  # 嵌套规则
  Advertising:
    <<: *classical
    url: "https://ghp.ci/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Advertising/Advertising.yaml"
    path: ./ruleset/Advertising.yaml

  AdvertisingMiTV:
    <<: *classical
    url: "https://ghp.ci/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/AdvertisingMiTV/AdvertisingMiTV.yaml"
    path: ./ruleset/AdvertisingMiTV.yaml

  ASNChina:
    <<: *classical
    url: "https://ghp.ci/https://raw.githubusercontent.com/VirgilClyne/GetSomeFries/main/ruleset/ASN.China.yaml"
    path: ./ruleset/ASNChina.yaml

  BanAD:
    <<: *classical
    url: "https://ghp.ci/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/BanAD.yaml"
    path: ./ruleset/BanAD.yaml

  BanEasyList:
    <<: *classical
    url: "https://ghp.ci/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/BanEasyList.yaml"
    path: ./ruleset/BanEasyList.yaml

  BanEasyListChina:
    <<: *classical
    url: "https://ghp.ci/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/BanEasyListChina.yaml"
    path: ./ruleset/BanEasyListChina.yaml

  BanEasyPrivacy:
    <<: *classical
    url: "https://ghp.ci/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/BanEasyPrivacy.yaml"
    path: ./ruleset/BanEasyPrivacy.yaml

  BanProgramAD:
    <<: *classical
    url: "https://ghp.ci/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/BanProgramAD.yaml"
    path: ./ruleset/BanProgramAD.yaml
    
  UnBan:
    <<: *classical
    url: "https://ghp.ci/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/UnBan.yaml"
    path: ./ruleset/UnBan.yaml
  
  Apple:
    <<: *classical
    url: "https://ghp.ci/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/Apple.yaml"
    path: ./ruleset/Apple.yaml

  ChinaDomain:
    <<: *classical
    url: "https://ghp.ci/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/ChinaDomain.yaml"
    path: ./ruleset/ChinaDomain.yaml

  ChinaIpV6:
    <<: *classical
    url: "https://ghp.ci/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/ChinaIpV6.yaml"
    path: ./ruleset/ChinaIpV6.yaml
    
  ChinaMedia:
    <<: *classical
    url: "https://ghp.ci/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/ChinaMedia.yaml"
    path: ./ruleset/ChinaMedia.yaml
    
  Download:
    <<: *classical
    url: "https://ghp.ci/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/Download.yaml"
    path: ./ruleset/Download.yaml
    
  LocalAreaNetwork:
    <<: *classical
    url: "https://ghp.ci/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/LocalAreaNetwork.yaml"
    path: ./ruleset/LocalAreaNetwork.yaml
    
  MJJ:
    <<: *classical
    url: "https://ghp.ci/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/MJJ.yaml"
    path: ./ruleset/MJJ.yaml
    
  ProxyGFWlist:
    <<: *classical
    url: "https://ghp.ci/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/ProxyGFWlist.yaml"
    path: ./ruleset/ProxyGFWlist.yaml
    
  ProxyLite:
    <<: *classical
    url: "https://ghp.ci/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/ProxyLite.yaml"
    path: ./ruleset/ProxyLite.yaml
    
  ProxyMedia:
    <<: *classical
    url: "https://ghp.ci/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/ProxyMedia.yaml"
    path: ./ruleset/ProxyMedia.yaml
