mixed-port: 7890
unified-delay: false
geodata-mode: true
tcp-concurrent: false
find-process-mode: strict
global-client-fingerprint: chrome

allow-lan: true
mode: rule
log-level: info
ipv6: true

external-controller: 127.0.0.1:9090

geox-url:
  geoip: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat"
  geosite: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat"
  mmdb: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/country.mmdb"

profile:
  store-selected: true
  store-fake-ip: true

sniffer:
  enable: false
  sniff:
    TLS:
      ports: [443]
    HTTP:
      ports: [80]
      override-destination: true

tun:
  enable: true
  stack: system
  dns-hijack:
    - 'any:53'
  auto-route: true
  auto-detect-interface: true

dns:
  enable: true
  listen: 0.0.0.0:1053
  ipv6: true
  enhanced-mode: fake-ip
  fake-ip-range: 28.0.0.1/8
  fake-ip-filter:
    - '*'
    - '+.lan'
  default-nameserver:
    - 223.5.5.5
  nameserver:
    - 'tls://8.8.4.4#DNS_Proxy'
    - 'tls://1.0.0.1#DNS_Proxy'
  proxy-server-nameserver:
    - https://dns.alidns.com/dns-query#h3=true
  nameserver-policy:
    "geosite:cn,private":
      - 223.5.5.5
      - 114.114.114.114
      - https://dns.alidns.com/dns-query#h3=true

proxy-providers:
  lkglbtenqc_provider:
    type: http
    path: ./lkglbtenqc_provider.yaml
    url: https://mirror.ghproxy.com/https://raw.githubusercontent.com/Lycofuture/Linux-install/main/meta.config
    interval: 3600
    health-check:
      enable: false
      url: http://www.gstatic.com/generate_204
      interval: 300
  mianfei:
    type: http
    path: ./mianfei.yaml
    url: https://fku-ppg.co.uk/
    interval: 3600
    health-check:
      enable: false
      url: http://www.gstatic.com/generate_204
      interval: 300
  mianfei2:
    type: http
    path: ./mianfei2.yaml
    url: https://mirror.ghproxy.com/https://raw.githubusercontent.com/mfbpn/tg_mfbpn_sub/main/trial.yaml
    interval: 3600
    health-check:
      enable: false
      url: http://www.gstatic.com/generate_204
      interval: 300
  mianfei3:
    type: http
    path: ./mianfei3.yaml
    url: https://api.ytools.cc/sub?target=clash&new_name=true&url=https://raw.githubusercontent.com/Alizhangs/kuaileshiguang/main/README.md&insert=false&config=https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/config/ACL4SSR_Online_Mini.ini
    interval: 3600
    health-check:
      enable: false
      url: http://www.gstatic.com/generate_204
      interval: 300
  mianfei4:
    type: http
    path: ./mianfei4.yaml
    url: https://api.ytools.cc/sub?target=clash&new_name=true&url=https://jiang.netlify.app/&insert=false&config=https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/config/ACL4SSR_Online_Mini.ini
    interval: 3600
    health-check:
      enable: false
      url: http://www.gstatic.com/generate_204
      interval: 300
  mianfei5:
    type: http
    path: ./mianfei5.yaml
    url: https://api.ytools.cc/sub?target=clash&new_name=true&url=https://api.yebekhe.link/telegramDonated/&insert=false&config=https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/config/ACL4SSR_Online_Mini.ini
    interval: 3600
    health-check:
      enable: false
      url: http://www.gstatic.com/generate_204
      interval: 300
  v2ray:
    type: http
    path: ./v2ray.yaml
    url: https://api.ytools.cc/sub?target=clash&new_name=true&url=https://eliv2ray.cloud/subscribe/eLiV2ray/-channel-eLiV2ray.txt&insert=false&config=https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/config/ACL4SSR_Online_Mini.ini
    interval: 3600
    health-check:
      enable: false
      url: http://www.gstatic.com/generate_204
      interval: 300
proxy-groups:
  - name: 手动切换
    type: select
    use:
      - lkglbtenqc_provider
      - mianfei
      - mianfei2
      - mianfei3
      - mianfei4
      - mianfei5
      - v2ray
    proxies: null
  - name: 自动选择
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 36000
    tolerance: 50
    use:
      - lkglbtenqc_provider
      - mianfei
      - mianfei2
      - mianfei3
      - mianfei4
      - mianfei5
      - v2ray
    proxies: null
  - name: 全球代理
    type: select
    use:
      - lkglbtenqc_provider
      - mianfei
      - mianfei2
      - mianfei3
      - mianfei4
      - mianfei5
      - v2ray
    proxies:
      - 手动切换
      - 自动选择
  - name: 流媒体
    type: select
    use:
      - lkglbtenqc_provider
      - mianfei
      - mianfei2
      - mianfei3
      - mianfei4
      - mianfei5
      - v2ray
    proxies:
      - 手动切换
      - 自动选择
      - DIRECT
  - name: DNS_Proxy
    type: select
    use:
      - lkglbtenqc_provider
      - mianfei
      - mianfei2
      - mianfei3
      - mianfei4
      - mianfei5
      - v2ray
    proxies:
      - 自动选择
      - DIRECT
  - name: Telegram
    type: select
    use:
      - lkglbtenqc_provider
      - mianfei
      - mianfei2
      - mianfei3
      - mianfei4
      - mianfei5
      - v2ray
    proxies:
      - 手动切换
      - 自动选择
  - name: Google
    type: select
    use:
      - lkglbtenqc_provider
      - mianfei
      - mianfei2
      - mianfei3
      - mianfei4
      - mianfei5
      - v2ray
    proxies:
      - 手动切换
      - 自动选择
      - DIRECT
  - name: YouTube
    type: select
    use:
      - lkglbtenqc_provider
      - mianfei
      - mianfei2
      - mianfei3
      - mianfei4
      - mianfei5
      - v2ray
    proxies:
      - 手动切换
      - 自动选择
  - name: Netflix
    type: select
    use:
      - lkglbtenqc_provider
      - mianfei
      - mianfei2
      - mianfei3
      - mianfei4
      - mianfei5
      - v2ray
    proxies:
      - 流媒体
      - 手动切换
      - 自动选择
  - name: Spotify
    type: select
    use:
      - lkglbtenqc_provider
      - mianfei
      - mianfei2
      - mianfei3
      - mianfei4
      - mianfei5
      - v2ray
    proxies:
      - 流媒体
      - 手动切换
      - 自动选择
      - DIRECT
  - name: HBO
    type: select
    use:
      - lkglbtenqc_provider
      - mianfei
      - mianfei2
      - mianfei3
      - mianfei4
      - mianfei5
      - v2ray
    proxies:
      - 流媒体
      - 手动切换
      - 自动选择
  - name: Bing
    type: select
    use:
      - lkglbtenqc_provider
      - mianfei
      - mianfei2
      - mianfei3
      - mianfei4
      - mianfei5
      - v2ray
    proxies:
      - 自动选择
  - name: OpenAI
    type: select
    use:
      - lkglbtenqc_provider
      - mianfei
      - mianfei2
      - mianfei3
      - mianfei4
      - mianfei5
      - v2ray
    proxies:
      - 自动选择
      - 手动切换
  - name: Disney
    type: select
    use:
      - lkglbtenqc_provider
      - mianfei
      - mianfei2
      - mianfei3
      - mianfei4
      - mianfei5
      - v2ray
    proxies:
      - 流媒体
      - 手动切换
      - 自动选择
  - name: GitHub
    type: select
    use:
      - lkglbtenqc_provider
      - mianfei
      - mianfei2
      - mianfei3
      - mianfei4
      - mianfei5
      - v2ray
    proxies:
      - 手动切换
      - 自动选择
      - DIRECT
  - name: 国内媒体
    type: select
    use:
      - lkglbtenqc_provider
      - mianfei
      - mianfei2
      - mianfei3
      - mianfei4
      - mianfei5
      - v2ray
    proxies:
      - DIRECT
  - name: 本地直连
    type: select
    use:
      - lkglbtenqc_provider
      - mianfei
      - mianfei2
      - mianfei3
      - mianfei4
      - mianfei5
      - v2ray
    proxies:
      - DIRECT
      - 自动选择
  - name: 漏网之鱼
    type: select
    use:
      - lkglbtenqc_provider
      - mianfei
      - mianfei2
      - mianfei3
      - mianfei4
      - mianfei5
      - v2ray
    proxies:
      - DIRECT
      - 手动切换
      - 自动选择
rule-providers:
  lan:
    type: http
    behavior: classical
    interval: 86400
    url: https://mirror.ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Lan/Lan.yaml
    path: ./Rules/lan.yaml
  reject:
    type: http
    behavior: domain
    url: https://mirror.ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/reject.txt
    path: ./ruleset/reject.yaml
    interval: 86400
  proxy:
    type: http
    behavior: domain
    url: https://mirror.ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/proxy.txt
    path: ./ruleset/proxy.yaml
    interval: 86400
  direct:
    type: http
    behavior: domain
    url: https://mirror.ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/direct.txt
    path: ./ruleset/direct.yaml
    interval: 86400
  private:
    type: http
    behavior: domain
    url: https://mirror.ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/private.txt
    path: ./ruleset/private.yaml
    interval: 86400
  gfw:
    type: http
    behavior: domain
    url: https://mirror.ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/gfw.txt
    path: ./ruleset/gfw.yaml
    interval: 86400
  greatfire:
    type: http
    behavior: domain
    url: https://mirror.ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/greatfire.txt
    path: ./ruleset/greatfire.yaml
    interval: 86400
  tld-not-cn:
    type: http
    behavior: domain
    url: https://mirror.ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/tld-not-cn.txt
    path: ./ruleset/tld-not-cn.yaml
    interval: 86400
  telegramcidr:
    type: http
    behavior: ipcidr
    url: https://mirror.ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/telegramcidr.txt
    path: ./ruleset/telegramcidr.yaml
    interval: 86400
  applications:
    type: http
    behavior: classical
    url: https://mirror.ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/applications.txt
    path: ./ruleset/applications.yaml
    interval: 86400
  Disney:
    type: http
    behavior: classical
    url: https://mirror.ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Disney/Disney.yaml
    path: ./ruleset/disney.yaml
    interval: 86400
  Netflix:
    type: http
    behavior: classical
    url: https://mirror.ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Netflix/Netflix.yaml
    path: ./ruleset/netflix.yaml
    interval: 86400
  YouTube:
    type: http
    behavior: classical
    url: https://mirror.ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/YouTube/YouTube.yaml
    path: ./ruleset/youtube.yaml
    interval: 86400
  HBO:
    type: http
    behavior: classical
    url: https://mirror.ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/HBO/HBO.yaml
    path: ./ruleset/hbo.yaml
    interval: 86400
  OpenAI:
    type: http
    behavior: classical
    url: https://mirror.ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OpenAI/OpenAI.yaml
    path: ./ruleset/openai.yaml
    interval: 86400
  Bing:
    type: http
    behavior: classical
    url: https://mirror.ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Bing/Bing.yaml
    path: ./ruleset/bing.yaml
    interval: 86400
  Google:
    type: http
    behavior: classical
    url: https://mirror.ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Google/Google.yaml
    path: ./ruleset/google.yaml
    interval: 86400
  GitHub:
    type: http
    behavior: classical
    url: https://mirror.ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GitHub/GitHub.yaml
    path: ./ruleset/github.yaml
    interval: 86400
  Spotify:
    type: http
    behavior: classical
    url: https://mirror.ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Spotify/Spotify.yaml
    path: ./ruleset/spotify.yaml
    interval: 86400
  ChinaMaxDomain:
    type: http
    behavior: domain
    interval: 86400
    url: https://mirror.ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaMax/ChinaMax_Domain.yaml
    path: ./Rules/ChinaMaxDomain.yaml
  ChinaMaxIPNoIPv6:
    type: http
    behavior: ipcidr
    interval: 86400
    url: https://mirror.ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaMax/ChinaMax_IP_No_IPv6.yaml
    path: ./Rules/ChinaMaxIPNoIPv6.yaml
rules:
  - RULE-SET,YouTube,YouTube,no-resolve
  - RULE-SET,Google,Google,no-resolve
  - RULE-SET,GitHub,GitHub
  - RULE-SET,telegramcidr,Telegram,no-resolve
  - RULE-SET,Spotify,Spotify,no-resolve
  - RULE-SET,Netflix,Netflix
  - RULE-SET,HBO,HBO
  - RULE-SET,Bing,Bing
  - RULE-SET,OpenAI,OpenAI
  - RULE-SET,Disney,Disney
  - RULE-SET,proxy,全球代理
  - RULE-SET,gfw,全球代理
  - RULE-SET,applications,本地直连
  - RULE-SET,ChinaMaxDomain,本地直连
  - RULE-SET,ChinaMaxIPNoIPv6,本地直连,no-resolve
  - RULE-SET,lan,本地直连,no-resolve
  - GEOIP,CN,本地直连
  - MATCH,漏网之鱼
