port: 7890
allow-lan: true
mode: rule
log-level: info
unified-delay: true
global-client-fingerprint: chrome
dns:
  enable: true
  listen: :53
  ipv6: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  default-nameserver:
    - 223.5.5.5
    - 8.8.8.8
  nameserver:
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
  fallback:
    - https://1.0.0.1/dns-query
    - tls://dns.google
  fallback-filter:
    geoip: true
    geoip-code: CN
    ipcidr:
      - 240.0.0.0/4
proxies:
- name: vless-reality-vision节点
  type: vless
  server: 185.77.225.87
  port: 61885
  uuid: 79941fc5-955f-482c-95ca-482fee3959f8
  network: tcp
  udp: true
  tls: true
  flow: xtls-rprx-vision
  servername: www.yahoo.com
  reality-opts:
    public-key: TYuqH5UdiRhXqg8GAGn3IruHdymFghuIe8TlNky8-lM
    short-id: 14387e0e
  client-fingerprint: chrome
- name: vmess-ws节点
  type: vmess
  server: 185.77.225.87
  port: 2052
  uuid: 79941fc5-955f-482c-95ca-482fee3959f8
  alterId: 0
  cipher: auto
  udp: true
  tls: false
  network: ws
  servername: www.bing.com
  ws-opts:
    path: "79941fc5-955f-482c-95ca-482fee3959f8-vm"
    headers:
      Host: www.bing.com
- name: hysteria2节点
  type: hysteria2
  server: 185.77.225.87
  port: 4445
  password: 79941fc5-955f-482c-95ca-482fee3959f8
  alpn:
    - h3
  sni: www.bing.com
  skip-cert-verify: true
  fast-open: true
- name: tuic5节点
  server: 185.77.225.87
  port: 50683
  type: tuic
  uuid: 79941fc5-955f-482c-95ca-482fee3959f8
  password: 79941fc5-955f-482c-95ca-482fee3959f8
  alpn: [h3]
  disable-sni: true
  reduce-rtt: true
  udp-relay-mode: native
  congestion-controller: bbr
  sni: www.bing.com
  skip-cert-verify: true
- name: Hys-hy
  type: hysteria
  server: 185.77.225.87
  ports: 47000-48000
  auth_str: eN3FBCXCJjfyUzUpxlfCfb6ZNSLveBILdtW8P2dTCvl5GQVu2t
  alpn:
    - h3
  protocol: udp
  up: 11
  down: 55
  sni: wechat.com
  skip-cert-verify: true
  recv_window_conn: 5767168
  recv_window: 23068672
  disable_mtu_discovery: true
  fast-open: true
- name: ssr
  type: ssr
  server: 185.77.225.87
  port: 37053
  password: KDStOaBPYVVpG5Dg
  cipher: aes-256-cfb
  obfs: plain
  protocol: origin
- name: ss
  type: ss
  server: 185.77.225.87
  port: 56899
  password: 9rQiI7XQFdaOJxw1
  cipher: aes-256-gcm
proxy-groups:
- name: 负载均衡
  type: load-balance
  url: https://cp.cloudflare.com/generate_204
  interval: 300
  strategy: round-robin
  proxies:
    - vless-reality-vision节点
    - vmess-ws节点
    - hysteria2节点
    - tuic5节点
    - Hys-hy
    - ssr
    - ss
- name: 自动选择
  type: url-test
  url: https://cp.cloudflare.com/generate_204
  interval: 300
  tolerance: 50
  proxies:
    - vless-reality-vision节点
    - vmess-ws节点
    - hysteria2节点
    - tuic5节点
    - Hys-hy
    - ssr
    - ss
- name: 🌍选择代理节点
  type: select
  proxies:
    - 负载均衡
    - 自动选择
    - vless-reality-vision节点
    - vmess-ws节点
    - hysteria2节点
    - tuic5节点
    - Hys-hy
    - ssr
    - ss
rules:
  - GEOIP,LAN,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,🌍选择代理节点
